/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CastlesIndexRouteImport } from './routes/castles.index'
import { Route as CastlesSlugRouteImport } from './routes/castles.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CastlesIndexRoute = CastlesIndexRouteImport.update({
  id: '/castles/',
  path: '/castles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CastlesSlugRoute = CastlesSlugRouteImport.update({
  id: '/castles/$slug',
  path: '/castles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/castles/$slug': typeof CastlesSlugRoute
  '/castles/': typeof CastlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/castles/$slug': typeof CastlesSlugRoute
  '/castles': typeof CastlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/castles/$slug': typeof CastlesSlugRoute
  '/castles/': typeof CastlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/castles/$slug' | '/castles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/castles/$slug' | '/castles'
  id: '__root__' | '/' | '/contact' | '/castles/$slug' | '/castles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CastlesSlugRoute: typeof CastlesSlugRoute
  CastlesIndexRoute: typeof CastlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/castles/': {
      id: '/castles/'
      path: '/castles'
      fullPath: '/castles/'
      preLoaderRoute: typeof CastlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/castles/$slug': {
      id: '/castles/$slug'
      path: '/castles/$slug'
      fullPath: '/castles/$slug'
      preLoaderRoute: typeof CastlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CastlesSlugRoute: CastlesSlugRoute,
  CastlesIndexRoute: CastlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
